site_name: Celldega Documentation
theme:
  name: material
  favicon: assets/img/celldega_logo_32x32_transparent.png
  logo: assets/img/Celldega_LOGO_Two-Color_Transparent_Logo Mark.png
  # logo: assets/img/assets/img/celldega_logo_32x32_transparent.png
  features:
    - navigation.indexes

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/broadinstitute/celldega"
    - icon: "fontawesome/brands/bluesky"
      link: "https://bsky.app/profile/stp-broad.bsky.social"

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Installation: installation.md
  - File Formats:
      - file_formats/index.md
      - file_formats/row_groups.md
  - Usage: usage.md
  - Python API:
      - python/index.md
      - pre: python/pre/api.md
      - clust: python/clust/api.md
      - nbhd: python/nbhd/api.md
      - viz: python/viz/api.md
  - JavaScript API:
      - javascript/index.md
      - API: javascript/api.md
  - Technologies:
      - technologies/index.md
      - Cloud:
        - cloud/index.md
        - Manifold:
            - Tutorial for generating LandscapeFiles: cloud/Manifold/Tutorial_for_generating_LandscapeFiles.md
        - Terra:
            - Tutorial for generating LandscapeFiles: cloud/Terra/Tutorial_for_generating_LandscapeFiles.md
            - Cell Segmentation on Terra: cloud/Terra/Cell_Segmentation_on_Terra.md
  - Gallery:
      - gallery/index.md
      - Xenium:
          - Xenium Prime Mouse Brain: gallery/gallery_xenium_mouse_brain.md
          - Xenium Prime Human Skin: gallery/gallery_xenium_skin_cancer.md
          - Xenium Multi Dataset: gallery/gallery_xenium_multi.md
      - Linked Views:
          - Landscape-Clustergram: gallery/gallery_landscape_clustergram.md
          - Landscape-Yearbook: gallery/gallery_landscape_yearbook.md
  - Tutorials:
    - tutorials/index.md
    - Guided Notebooks:
      - Scanpy-Squidpy Xenium Pancreas: tutorials/guided_notebooks/Scanpy-Squidpy_Xenium_Pancreas.ipynb
      - Chromium Pre-process: tutorials/guided_notebooks/Scanpy_Chromium.ipynb
      - Single-cell Clustergram Chromium: tutorials/guided_notebooks/Single-Cell_Clustergram_Chromium.ipynb
      - Visium-HD Landscape Pre-process: tutorials/guided_notebooks/Visium-HD_Landscape_Pre-process.ipynb
      - Comparison of domain identification algorithms in Celldega: tutorials/guided_notebooks/domain_comparison-Celldega_w_external_algorithms.ipynb
    - Quick Notebooks:
      - Landscape View Xenium: tutorials/quick_notebooks/Landscape_View_Xenium.ipynb
      - Landscape-Heatmap Visium-HD: tutorials/quick_notebooks/Landscape-Heatmap-Visium-HD.ipynb
      - UMAP-Cluster Pancreas Xenium: tutorials/quick_notebooks/UMAP-Cluster_Pancreas_Xenium.ipynb
      - Visium-HD Landscape Mouse Lung: tutorials/quick_notebooks/Visium-HD_Landscape_Mouse_Lung_FF.ipynb
      - Custom Segmentation: tutorials/quick_notebooks/Custom_Segmentation.ipynb
      - Yearbook-Query: tutorials/quick_notebooks/Yearbook_Query.ipynb

markdown_extensions:
  - toc
  - tables
  - admonition
  - attr_list
  - md_in_html


plugins:
  - search
  - open-in-new-tab
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_toc_entry: true
  - mkdocs-jupyter:
      include_source: true
      include_requirejs: true
      ignore: ["**/.ipynb_checkpoints/*.ipynb"]

extra_javascript:
  - path: assets/js/index.js
    type: module
  - path: assets/js/gallery_mouse_brain.js
    type: module
  - path: assets/js/gallery_skin_cancer.js
    type: module
  - path: assets/js/google-analytics.js
  - path: assets/js/hide_notebook_sidebar.js
    type: module
  - path: assets/js/gallery_visium_hd_cell_segmentation_mouse_brain.js
    type: module
  - path: assets/js/gallery_visium_hd_human_kidney.js
    type: module
  - path: assets/js/gallery_visium_hd_pancreas.js
    type: module
  - path: assets/js/gallery_landscape_clustergram.js
    type: module
  - path: assets/js/gallery_landscape_yearbook.js
    type: module

extra_css:
  - assets/css/custom.css