site_name: Celldega Documentation
theme:
  name: material
  features:
    - navigation.indexes

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/broadinstitute/celldega"
    - icon: "fontawesome/brands/bluesky"
      link: "https://bsky.app/profile/stp-broad.bsky.social"

nav:
  - Home: index.md
  - Overview:
      - Getting Started: getting_started.md
      - Installation: installation.md
      - Usage: usage.md
  - Python API:
      - Overview: python/overview.md
      - pre: python/pre/api.md
      - viz: python/viz/api.md

  - JavaScript API:
      - Overview: javascript/overview.md
      - API: javascript/api.md
  - Technologies:
      - technologies/index.md
      - technologies/parquet.md
  - Gallery:
      - Overview: gallery/overview.md
      - Gallery Xenium:
          - Xenium Prime Mouse Brain: gallery/gallery_xenium_mouse_brain.md
          - Xenium Prime Human Skin: gallery/gallery_xenium_skin_cancer.md
          - Xenium Multi Dataset: gallery/gallery_xenium_multi.md
  - Example Notebooks:
    - Overview: examples/overview.md
    - Short Notebooks:

      - Landscape View Xenium: examples/short_notebooks/Landscape_View_Xenium.ipynb
    # - Tutorials:
    #     - examples/Landscape_View_Xenium.ipynb

markdown_extensions:
  - toc
  - tables
  - admonition


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_toc_entry: true
        javascript:
          options:
            source: js/  # Path to JavaScript files
            recursive: true
            include: .+\.js$
  - mkdocs-jupyter:
      include_source: true
      ignore: ["**/.ipynb_checkpoints/*.ipynb"]

extra_javascript:
  - path: assets/js/index.js
    type: module
  - path: assets/js/gallery_mouse_brain.js
    type: module
  - path: assets/js/gallery_skin_cancer.js
    type: module
  - path: assets/js/google-analytics.js
