site_name: Celldega Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Overview:
      - Getting Started: getting_started.md
      - Installation: installation.md
      - Usage: usage.md
  - Gallery:
      - Gallery Xenium:
          - Xenium Prime Mouse Brain: gallery_xenium_mouse_brain.md
          - Xenium Prime Human Skin: gallery_xenium_human_skin.md
          - Xenium Multi Dataset: gallery_xenium_multi.md
  - Python API:
      - pre:
          - Overview: python/pre/overview.md
          - API Reference: python/pre/api.md
      - viz:
          - Overview: python/viz/overview.md
          - API Reference: python/viz/api.md
  - JavaScript API:
      - Overview: javascript/overview.md
      - API Reference: javascript/api.md
  - Examples:
      - examples/Landscape_View_Xenium.ipynb

markdown_extensions:
  - toc
  - tables
  - admonition

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_toc_entry: true
        javascript:
          options:
            source: js/  # Path to JavaScript files
            recursive: true
            include: .+\.js$
  - mkdocs-jupyter:
      include_source: true
      ignore: ["**/.ipynb_checkpoints/*.ipynb"]

extra_javascript:
  - path: assets/js/index.js
    type: module
  - path: assets/js/gallery_mouse_brain.js
    type: module
  - path: assets/js/google-analytics.js
