blank_issues_enabled: true
contact_links:
  - name: Questions & Support
    url: https://github.com/broadinstitute/celldega/discussions
    about: Ask questions and discuss with other Celldega users in GitHub Discussions.
